name: 'Danger JS'
on: [pull_request_target]

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/checkout@v4
      - name: Install
        run: pnpm install
      - name: Danger
        uses: danger/danger-js@10.6.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
